{
  "content": "def _profileFunc(numFrames: int = numFrames) -> None:\n                            self._doProfiledFrames(numFrames)\n                        session.setFunc(_profileFunc)\n                        session.run()\n                        del _profileFunc\n                        if callback:\n                            callback()\n                        session.release()\n                    else:\n                        self.step()\n                except KeyboardInterrupt:\n                    self.stop()\n                except SystemExit:\n                    self.stop()\n                    raise\n                except IOError as ioError:\n                    code, message = self._unpackIOError(ioError)\n                    # Since upgrading to Python 2.4.1, pausing the execution\n                    # often gives this IOError during the sleep function:\n                    #     IOError: [Errno 4] Interrupted function call",
  "metadata": {
    "doc_type": "python",
    "doc_id": "doc_210",
    "parent": "processed_documents/context_documents/3377b266_Task.json",
    "chunk_number": 3895
  }
}